'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight, ArrowRight, ScanLine, Plus, LayoutDashboard, History, Award, Sparkles, ChevronRight, Camera, Upload, X, Coffee, ShoppingBag, Car, Receipt, Clapperboard, MoreHorizontal, Search, Download, Check, Flame} from 'lucide-react';
import ReceiptScanner from '@/components/receipt-scanner';
import type { Receipt as ScannedReceipt } from '@/lib/receipt';
import {categories, Expense, money, localDate, demoExpenses, validExpense, streak} from '@/lib/expenses';
const icons=[Coffee,ShoppingBag,Car,Receipt,Clapperboard,MoreHorizontal];
const tabs=[['dashboard','Ringkasan',LayoutDashboard],['history','Riwayat',History],['achievements','Pencapaian',Award],['wrapped','Wrapped',Sparkles]] as const;
export default function Home(){
 const [tab,setTab]=useState('dashboard'),[expenses,setExpenses]=useState<Expense[]>([]),[demo,setDemo]=useState(true),[ready,setReady]=useState(false),[today,setToday]=useState(''),[month,setMonth]=useState(''),[search,setSearch]=useState(''),[filter,setFilter]=useState('Semua'),[notice,setNotice]=useState(''),[modal,setModal]=useState<'manual'|'scan'|null>(null),[scanning,setScanning]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null); const [merchant,setMerchant]=useState(''),[amount,setAmount]=useState(''),[category,setCategory]=useState<string>(categories[0]),[date,setDate]=useState('');
 useEffect(()=>{const now=localDate();setToday(now);setMonth(now.slice(0,7));setDate(now);try{const raw=localStorage.getItem('spendscan-v1');if(raw){const parsed=JSON.parse(raw);if(!Array.isArray(parsed)||!parsed.every(validExpense))throw Error();setExpenses(parsed);setDemo(false);}}catch{setNotice('Data tersimpan tidak dapat dibaca. Data belum ditimpa; coba muat ulang.');}setReady(true);},[]);
 useEffect(()=>{if(modal)dialog.current?.showModal();else dialog.current?.close();},[modal]);

 const data=demo?demoExpenses(today||'2026-09-17'):expenses;
 const current=data.filter(e=>e.date.startsWith(month)); const total=current.reduce((a,e)=>a+e.amount,0);
 const breakdown=categories.map((name,i)=>({name,i,value:current.filter(e=>e.category===name).reduce((a,e)=>a+e.amount,0)})).sort((a,b)=>b.value-a.value);
 const top=breakdown[0]; const days=new Set(current.map(e=>e.date)).size; const run=streak(data,today||'2026-09-17');
 const monthLabel=month?new Date(month+'-01T12:00:00').toLocaleDateString('id-ID',{month:'long',year:'numeric'}):'Memuat…';
 function open(kind:'manual'|'scan'){setMerchant('');setAmount('');setCategory(categories[0]);setDate(today);setScanning(false);setModal(kind);}
 function applyReceipt(r:ScannedReceipt|null){setMerchant(r?.merchant||'');setAmount(r?.currency==='IDR' && r.amount?String(r.amount):'');setCategory(r?.category||categories[0]);setDate(r?.date&&r.date<=today?r.date:'');}
 function persist(next:Expense[]){try{localStorage.setItem('spendscan-v1',JSON.stringify(next));setExpenses(next);setDemo(false);return true;}catch{setNotice('Penyimpanan browser penuh atau tidak tersedia. Transaksi belum disimpan.');return false;}}
 function save(e:React.FormEvent){e.preventDefault();if(scanning)return;const item={id:crypto.randomUUID(),merchant:merchant.trim(),amount:Number(amount),category,date};if(!item.merchant||!validExpense(item)||date>today)return; if(persist([item,...expenses])){setModal(null);setNotice('Pengeluaran tersimpan. Ringkasanmu sudah diperbarui.');setMonth(date.slice(0,7));}}
 function csv(){const content='Tanggal,Merchant,Kategori,Nominal\n'+current.map(e=>[e.date,e.merchant,e.category,e.amount].map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+content],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`spendscan-${month}${demo?'-contoh':''}.csv`;a.click();URL.revokeObjectURL(url);}
 const rows=current.filter(e=>e.merchant.toLowerCase().includes(search.toLowerCase())&&(filter==='Semua'||e.category===filter)).sort((a,b)=>b.date.localeCompare(a.date));
 const recentRows=[...current].sort((a,b)=>b.date.localeCompare(a.date));
 function transactions(items:Expense[],limit?:number){return items.length?<div className="transactions">{items.slice(0,limit).map(e=>{const Icon=icons[categories.indexOf(e.category as typeof categories[number])]||Receipt;return <div className="transaction" key={e.id}><span className="transaction-icon"><Icon size={21}/></span><div className="transaction-name"><strong>{e.merchant}</strong><small>{e.category}</small></div><time>{new Date(e.date+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short'})}</time><strong>{money(e.amount)}</strong></div>})}</div>:<div className="empty"><Receipt size={32}/><h3>Belum ada pengeluaran</h3><p>Catat transaksi pertamamu untuk mulai melihat polanya.</p><button className="primary" onClick={()=>open('manual')}>Tambah pengeluaran</button></div>}
 return <><header className="global"><div><span><ScanLine size={18}/> SpendScan</span><span>Kenali ke mana uangmu pergi.</span><span className="local-label">AI scanner</span></div></header><div className="subnav"><a href="#" className="brand" onClick={e=>{e.preventDefault();setTab('dashboard')}}><ScanLine/>SpendScan<span>®</span></a><nav aria-label="Navigasi utama">{tabs.map(([key,label,Icon])=><button key={key} aria-current={tab===key?'page':undefined} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}</button>)}</nav><button className="primary compact" onClick={()=>open('scan')}><ScanLine size={17}/><span className="scan-label-full">Scan struk</span><span className="scan-label-short">Scan</span></button></div>
 <main>{notice&&<div role="status" className="notice">{notice}<button aria-label="Tutup pemberitahuan" onClick={()=>setNotice('')}><X size={18}/></button></div>}<div className={`page-heading ${tab==='dashboard'?'':'compact-heading'}`}><div><p className="eyebrow">YOUR MONEY, A LITTLE CLEARER.</p><h1>{tab==='dashboard'?'Sedikit dicatat. Banyak dipahami.':tab==='history'?'Setiap transaksi, satu cerita.':tab==='achievements'?'Kebiasaan kecil. Langkah berarti.':'Ini cerita uangmu.'}</h1><p className="subtitle">{tab==='dashboard'?'Ruang untuk memahami pengeluaran, tanpa menghakimi.':tab==='history'?'Semua pengeluaranmu, rapi dalam satu tempat.':tab==='achievements'?'Rayakan konsistensi, satu catatan demi satu catatan.':'Lihat kembali hal-hal yang mengisi bulanmu.'}</p></div><label className="month-picker"><span>Bulan</span><input aria-label="Pilih bulan" type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value)}}/></label></div>
 <div className="modebar"><span>{demo?'Kamu sedang melihat data contoh.':'Data pribadi · tersimpan di browser ini.'}</span><button onClick={()=>{setDemo(!demo);setSearch('');setFilter('Semua')}}>{demo?'Gunakan data saya':'Lihat contoh'}<ArrowRight size={15}/></button></div>
 {!ready?<div className="empty">Menyiapkan ringkasanmu…</div>:<>
 {tab==='dashboard'&&<><section className="overview"><div className="spending-card"><div className="card-top"><span>Pengeluaran bulan ini</span><span className="period">{monthLabel}</span></div><div className="total">{money(total)}</div><p>{current.length} transaksi · {days} hari tercatat</p><div className="chart" aria-label="Pengeluaran mingguan"><div className="bars">{Array.from({length:5},(_,i)=>{const value=current.filter(e=>Math.min(4,Math.floor((Number(e.date.slice(-2))-1)/7))===i).reduce((a,e)=>a+e.amount,0);const peak=Math.max(1,...Array.from({length:5},(_,j)=>current.filter(e=>Math.min(4,Math.floor((Number(e.date.slice(-2))-1)/7))===j).reduce((a,e)=>a+e.amount,0)));return <div className="bar-col" key={i}><div className="bar" style={{height:`${Math.max(3,value/peak*100)}%`}} title={money(value)}><span>{money(value)}</span></div><small>{['1–7','8–14','15–21','22–28','29–31'][i]}</small></div>})}</div></div><div className="card-bottom"><span>Rata-rata per hari tercatat</span><strong>{money(days?total/days:0)}</strong></div></div><div className="scan-card"><span className="scan-symbol"><ScanLine size={38} strokeWidth={1.4}/></span><div><p className="eyebrow">LESS TYPING. MORE LIVING.</p><h2>Habis jajan? <br/>Catat sebentar.</h2><p>Satu struk, satu langkah untuk lebih kenal kebiasaanmu.</p></div><button className="primary" onClick={()=>open('scan')}><Camera size={19}/> Tambah dari struk<ArrowUpRight size={18}/></button><button className="text-button" onClick={()=>open('manual')}>Atau catat manual <ArrowRight size={16}/></button></div></section>
 <section className="stats"><div><span className="stat-icon"><Receipt/></span><div><small>Total transaksi</small><strong>{current.length}<em> transaksi</em></strong></div></div><div><span className="stat-icon"><ShoppingBag/></span><div><small>Pengeluaran terbesar</small><strong>{top?.value?top.name:'Belum ada'}<em>{top?.value?' · '+Math.round(top.value/total*100)+'%':''}</em></strong></div></div><div><span className="stat-icon"><Flame/></span><div><small>Konsistensi mencatat</small><strong>{run}<em> hari beruntun</em></strong></div></div></section>
 <section className="details-grid"><div className="panel"><div className="section-title"><div><h2>Ke mana uangmu pergi?</h2><p>Gambaran kecil, perspektif baru.</p></div></div><div className="category-list">{breakdown.filter(e=>e.value>0).map(({name,i,value})=>{const Icon=icons[i];return <div className="category" key={name}><Icon size={19}/><div><div className="category-label"><span>{name}</span><strong>{money(value)}</strong></div><div className="track"><span style={{width:`${value/total*100}%`,opacity:1-i*.1}}/></div></div><small>{Math.round(value/total*100)}%</small></div>})}{!total&&<p className="muted">Kategori akan muncul setelah kamu mencatat pengeluaran.</p>}</div></div><div className="panel"><div className="section-title"><div><h2>Baru saja dicatat</h2><p>Hal-hal kecil dalam keseharianmu.</p></div><button className="text-button icon-button" onClick={()=>setTab('history')} aria-label="Lihat semua riwayat"><ArrowUpRight size={22}/></button></div>{transactions(recentRows,4)}</div></section>
 <section className="wrapped-banner"><div><p className="eyebrow">YOUR MONTH. YOUR STORY.</p><h2>Setiap pengeluaran punya cerita.</h2><p>Temukan cerita bulanmu di Money Wrapped.</p></div><button onClick={()=>setTab('wrapped')}>Buka Wrapped<ArrowUpRight size={18}/></button></section></>}
 {tab==='history'&&<section className="panel"><div className="history-toolbar"><label className="search"><Search size={18}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari transaksi…" aria-label="Cari transaksi"/></label><select aria-label="Filter kategori" value={filter} onChange={e=>setFilter(e.target.value)}>{['Semua',...categories].map(c=><option key={c}>{c}</option>)}</select><button className="secondary" onClick={csv} aria-label="Ekspor CSV"><Download size={17}/><span className="export-long">Ekspor CSV</span><span className="export-short">CSV</span></button><button className="primary" onClick={()=>open('manual')}><Plus size={18}/> Tambah</button></div>{transactions(rows)}</section>}
 {tab==='achievements'&&<div className="achievement-grid">{[{name:'Langkah pertama',text:'Catat pengeluaran pertamamu.',goal:1,n:data.length,Icon:Receipt},{name:'Mulai terbiasa',text:'Kumpulkan 10 catatan pengeluaran.',goal:10,n:data.length,Icon:Check},{name:'Seminggu konsisten',text:'Mencatat selama 7 hari beruntun.',goal:7,n:run,Icon:Flame},{name:'Makin mengenal diri',text:'Kumpulkan 50 catatan pengeluaran.',goal:50,n:data.length,Icon:Award}].map(({name,text,goal,n,Icon})=><div className={'panel badge '+(n>=goal?'earned':'')} key={name}><span><Icon size={36}/></span><h2>{name}</h2><p>{text}</p><strong>{n>=goal?'Tercapai':`${Math.min(n,goal)} / ${goal}`}</strong><progress max={goal} value={Math.min(n,goal)}/></div>)}</div>}
 {tab==='wrapped'&&<section className="wrapped-page"><span className="eyebrow">SPENDSCAN · {demo?'CONTOH · ':''}{monthLabel.toUpperCase()}</span><h2>Uangmu pergi. <br/>Ceritanya tinggal.</h2><p>Bulan ini kamu mencatat</p><strong className="wrapped-total">{money(total)}</strong><div className="wrapped-stats"><div><strong>{current.length}</strong><span>transaksi tercatat</span></div><div><strong>{top?.value?Math.round(top.value/total*100):0}%</strong><span>{top?.value?top.name:'belum ada kategori'}</span></div><div><strong>{days}</strong><span>hari yang kamu catat</span></div></div><p>{top?.value?`${top.name} jadi bagian terbesar bulan ini. Mengenali pola adalah langkah awal.`:'Mulai catat pengeluaran untuk menemukan cerita bulanmu.'}</p><button className="primary" onClick={async()=>{const text=`${demo?'Contoh ':''}SpendScan Wrapped — ${monthLabel}\n${money(total)} · ${current.length} transaksi\nKategori terbesar: ${top?.value?top.name:'Belum ada'}`;try{await navigator.clipboard.writeText(text);setNotice('Ringkasan Wrapped disalin. Siap kamu bagikan.');}catch{setNotice('Browser tidak mengizinkan penyalinan. Kamu bisa menyalin ringkasan dari halaman ini.');}}}>Salin cerita bulan ini <ArrowUpRight size={18}/></button></section>}
 </>}<footer><span><ScanLine size={16}/> SpendScan</span><span>Lebih sadar. Lebih tenang.</span><small>Data lokal di perangkatmu.</small></footer></main>
 <dialog ref={dialog} aria-labelledby="expense-dialog-title" onCancel={()=>setModal(null)} onClick={e=>{if(e.target===dialog.current)setModal(null)}}><div className="dialog-content"><button className="close" aria-label="Tutup" onClick={()=>setModal(null)}><X/></button><p className="eyebrow">SATU CATATAN KECIL.</p><h2 id="expense-dialog-title">{modal==='scan'?'Dari struk ke catatan.':'Tambah pengeluaran'}</h2>{demo&&<p className="form-note">Transaksi baru masuk ke data pribadimu. Data contoh tidak ikut disimpan.</p>}{modal==='scan'&&<ReceiptScanner onResult={applyReceipt} onBusy={setScanning}/>}<form onSubmit={save}><fieldset disabled={scanning} className="expense-fields"><label>Merchant / pengeluaran<input required maxLength={100} autoFocus={modal==='manual'} placeholder="Contoh: Kopi Tuku" value={merchant} onChange={e=>setMerchant(e.target.value)}/></label><label>Nominal (Rp)<input required type="number" min="1" max="999999999999" step="1" inputMode="numeric" placeholder="28000" value={amount} onChange={e=>setAmount(e.target.value)}/></label><div className="form-row"><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label><label>Tanggal<input required type="date" max={today} value={date} onChange={e=>setDate(e.target.value)}/></label></div><button type="submit" className="primary"><Check size={18}/> Konfirmasi & simpan</button></fieldset></form></div></dialog></>;
}
